#!/bin/bash
# screensaver-ctl.sh - Management script for COSMIC screensaver
# Handles configuration, swayidle integration, and power settings

set -uo pipefail

# Paths
SCREENSAVER_DIR="${SCREENSAVER_DIR:-$HOME/.config/cosmic-screensaver}"
CONFIG_FILE="${SCREENSAVER_DIR}/config"
SWAYIDLE_CONFIG="${SCREENSAVER_DIR}/swayidle.conf"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
SCREENSAVER_SCRIPT="${SCRIPT_DIR}/cosmic-screensaver.sh"
FULLSCREEN_LAUNCHER="${SCRIPT_DIR}/launch-fullscreen.sh"

# Default settings
DEFAULT_IDLE_TIMEOUT=300      # 5 minutes
DEFAULT_LOCK_TIMEOUT=600      # 10 minutes (after screensaver)
DEFAULT_DPMS_TIMEOUT=900      # 15 minutes (screen off)
DEFAULT_FRAME_RATE=60
DEFAULT_INCLUDE_EFFECTS=""    # empty = use all (or exclude list)
DEFAULT_EXCLUDE_EFFECTS="dev_worm"
DEFAULT_FADE_IN_EFFECT=""     # e.g., expand, slide, middleout
DEFAULT_FADE_OUT_EFFECT=""    # e.g., burn, crumble, scattered
DEFAULT_SHOW_CLOCK="false"    # Show time between effects
DEFAULT_CLOCK_DURATION=3      # Seconds to display clock
DEFAULT_CLOCK_FORMAT="%H:%M"  # Time format
DEFAULT_CLOCK_FONT=""         # figlet/toilet font
DEFAULT_TERMINAL="ghostty"    # ghostty or cosmic-term
DEFAULT_LOCK_COMMAND="cosmic-greeter --lock"  # Lock screen command
DEFAULT_CURSOR_HIDE="true"    # Hide text cursor during screensaver
DEFAULT_HIDE_MOUSE="true"     # Hide mouse pointer via terminal config
DEFAULT_DISMISS_ON_KEY="true" # Keyboard input dismisses screensaver

# Cache for effect list (populated on first call)
EFFECTS_CACHE=""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info() { echo -e "${CYAN}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# Ensure directories exist
ensure_dirs() {
    mkdir -p "$SCREENSAVER_DIR"
    mkdir -p "$SYSTEMD_USER_DIR"
}

# Load current configuration
load_config() {
    # Set defaults
    ENABLED="${ENABLED:-true}"
    IDLE_TIMEOUT="${IDLE_TIMEOUT:-$DEFAULT_IDLE_TIMEOUT}"
    LOCK_TIMEOUT="${LOCK_TIMEOUT:-$DEFAULT_LOCK_TIMEOUT}"
    DPMS_TIMEOUT="${DPMS_TIMEOUT:-$DEFAULT_DPMS_TIMEOUT}"
    FRAME_RATE="${FRAME_RATE:-$DEFAULT_FRAME_RATE}"
    INCLUDE_EFFECTS="${INCLUDE_EFFECTS:-$DEFAULT_INCLUDE_EFFECTS}"
    EXCLUDE_EFFECTS="${EXCLUDE_EFFECTS:-$DEFAULT_EXCLUDE_EFFECTS}"
    FADE_IN_EFFECT="${FADE_IN_EFFECT:-$DEFAULT_FADE_IN_EFFECT}"
    FADE_OUT_EFFECT="${FADE_OUT_EFFECT:-$DEFAULT_FADE_OUT_EFFECT}"
    SHOW_CLOCK="${SHOW_CLOCK:-$DEFAULT_SHOW_CLOCK}"
    CLOCK_DURATION="${CLOCK_DURATION:-$DEFAULT_CLOCK_DURATION}"
    CLOCK_FORMAT="${CLOCK_FORMAT:-$DEFAULT_CLOCK_FORMAT}"
    CLOCK_FONT="${CLOCK_FONT:-$DEFAULT_CLOCK_FONT}"
    LOGO_FILE="${LOGO_FILE:-$SCREENSAVER_DIR/logo.txt}"
    DISABLE_ON_BATTERY="${DISABLE_ON_BATTERY:-false}"
    BATTERY_IDLE_TIMEOUT="${BATTERY_IDLE_TIMEOUT:-600}"
    TERMINAL="${TERMINAL:-$DEFAULT_TERMINAL}"
    LOCK_COMMAND="${LOCK_COMMAND:-$DEFAULT_LOCK_COMMAND}"
    CURSOR_HIDE="${CURSOR_HIDE:-$DEFAULT_CURSOR_HIDE}"
    HIDE_MOUSE="${HIDE_MOUSE:-$DEFAULT_HIDE_MOUSE}"
    DISMISS_ON_KEY="${DISMISS_ON_KEY:-$DEFAULT_DISMISS_ON_KEY}"

    if [[ -f "$CONFIG_FILE" ]]; then
        # shellcheck source=/dev/null
        source "$CONFIG_FILE"
    fi
}

# Save configuration
save_config() {
    cat > "$CONFIG_FILE" << EOF
# COSMIC Screensaver Configuration
# Generated by screensaver-ctl.sh

# Enable/disable screensaver
ENABLED="${ENABLED}"

# Idle timeout before screensaver starts (seconds)
IDLE_TIMEOUT="${IDLE_TIMEOUT}"

# Lock timeout after screensaver (seconds, 0 to disable)
LOCK_TIMEOUT="${LOCK_TIMEOUT}"

# DPMS (screen off) timeout (seconds, 0 to disable)
DPMS_TIMEOUT="${DPMS_TIMEOUT}"

# Animation frame rate (lower = less CPU)
FRAME_RATE="${FRAME_RATE}"

# Effects to include (comma-separated, takes precedence over exclude)
INCLUDE_EFFECTS="${INCLUDE_EFFECTS}"

# Effects to exclude (comma-separated, ignored if include is set)
EXCLUDE_EFFECTS="${EXCLUDE_EFFECTS}"

# Fade transition effects (empty to disable)
FADE_IN_EFFECT="${FADE_IN_EFFECT}"
FADE_OUT_EFFECT="${FADE_OUT_EFFECT}"

# Clock display between effects
SHOW_CLOCK="${SHOW_CLOCK}"
CLOCK_DURATION="${CLOCK_DURATION}"
CLOCK_FORMAT="${CLOCK_FORMAT}"
CLOCK_FONT="${CLOCK_FONT}"

# Logo file path
LOGO_FILE="${LOGO_FILE}"

# Power settings
DISABLE_ON_BATTERY="${DISABLE_ON_BATTERY}"
BATTERY_IDLE_TIMEOUT="${BATTERY_IDLE_TIMEOUT}"

# Terminal emulator (ghostty or cosmic-term)
TERMINAL="${TERMINAL}"

# Lock screen command (customize for different lock screens)
LOCK_COMMAND="${LOCK_COMMAND}"

# Cursor & input handling
CURSOR_HIDE="${CURSOR_HIDE}"
HIDE_MOUSE="${HIDE_MOUSE}"
DISMISS_ON_KEY="${DISMISS_ON_KEY}"
EOF
    log_success "Configuration saved to $CONFIG_FILE"
}

# Check power status
is_on_battery() {
    local status
    status=$(cat /sys/class/power_supply/BAT*/status 2>/dev/null | head -1)
    [[ "$status" == "Discharging" ]]
}

# Get effective idle timeout based on power status
get_effective_timeout() {
    if [[ "$DISABLE_ON_BATTERY" == "true" ]] && is_on_battery; then
        echo "$BATTERY_IDLE_TIMEOUT"
    else
        echo "$IDLE_TIMEOUT"
    fi
}

# Generate swayidle configuration
generate_swayidle_config() {
    local timeout
    timeout=$(get_effective_timeout)

    # Use fullscreen launcher
    local launch_cmd="${FULLSCREEN_LAUNCHER} launch"
    local kill_cmd="${FULLSCREEN_LAUNCHER} kill"

    cat > "$SWAYIDLE_CONFIG" << EOF
# Swayidle configuration for COSMIC Screensaver
# Generated by screensaver-ctl.sh
# Reload: systemctl --user restart cosmic-screensaver-idle.service

timeout ${timeout} '${launch_cmd}' resume '${kill_cmd}'
EOF

    # Add lock timeout if set
    if [[ "$LOCK_TIMEOUT" -gt 0 ]]; then
        local lock_time=$((timeout + LOCK_TIMEOUT))
        echo "timeout ${lock_time} '${LOCK_COMMAND}'" >> "$SWAYIDLE_CONFIG"
    fi

    # Add DPMS timeout if set (resume must be on same line as timeout)
    if [[ "$DPMS_TIMEOUT" -gt 0 ]]; then
        echo "timeout ${DPMS_TIMEOUT} 'cosmic-randr output \"*\" --off' resume 'cosmic-randr output \"*\" --on'" >> "$SWAYIDLE_CONFIG"
    fi

    # Handle before-sleep (system suspend)
    cat >> "$SWAYIDLE_CONFIG" << EOF
before-sleep '${LOCK_COMMAND}'
EOF

    log_success "Generated swayidle config: $SWAYIDLE_CONFIG"
}

# Create systemd user service for swayidle
create_systemd_service() {
    local service_file="${SYSTEMD_USER_DIR}/cosmic-screensaver-idle.service"

    cat > "$service_file" << EOF
[Unit]
Description=COSMIC Screensaver Idle Daemon
Documentation=https://github.com/swaywm/swayidle
PartOf=graphical-session.target
After=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/swayidle -w -C ${SWAYIDLE_CONFIG}
ExecReload=/bin/kill -HUP \$MAINPID
Restart=on-failure
RestartSec=5

[Install]
WantedBy=graphical-session.target
EOF

    log_success "Created systemd service: $service_file"
}

# Install swayidle if not present
check_swayidle() {
    if ! command -v swayidle &>/dev/null; then
        log_warn "swayidle is not installed."
        log_info "Install with: sudo apt install swayidle"
        return 1
    fi
    return 0
}

# Enable screensaver service
enable_service() {
    if ! check_swayidle; then
        return 1
    fi

    ensure_dirs
    load_config
    ENABLED="true"
    save_config
    generate_swayidle_config
    create_systemd_service

    systemctl --user daemon-reload
    systemctl --user enable cosmic-screensaver-idle.service
    systemctl --user start cosmic-screensaver-idle.service

    log_success "Screensaver enabled and started"
}

# Disable screensaver service
disable_service() {
    load_config
    ENABLED="false"
    save_config

    systemctl --user stop cosmic-screensaver-idle.service 2>/dev/null || true
    systemctl --user disable cosmic-screensaver-idle.service 2>/dev/null || true

    log_success "Screensaver disabled"
}

# Reload configuration
reload_service() {
    load_config
    generate_swayidle_config
    systemctl --user restart cosmic-screensaver-idle.service 2>/dev/null || true
    log_success "Configuration reloaded"
}

# Show current status
show_status() {
    load_config
    echo
    echo -e "${BOLD}COSMIC Screensaver Status${NC}"
    echo "─────────────────────────────────"

    # Service status
    local service_status
    if systemctl --user is-active cosmic-screensaver-idle.service &>/dev/null; then
        service_status="${GREEN}running${NC}"
    else
        service_status="${RED}stopped${NC}"
    fi
    echo -e "Service:          $service_status"
    echo -e "Enabled:          ${ENABLED}"
    echo

    # Timers
    echo -e "${BOLD}Timeouts${NC}"
    echo -e "Idle timeout:     ${IDLE_TIMEOUT}s ($(( IDLE_TIMEOUT / 60 )) min)"
    echo -e "Lock timeout:     ${LOCK_TIMEOUT}s ($(( LOCK_TIMEOUT / 60 )) min after idle)"
    echo -e "Screen off:       ${DPMS_TIMEOUT}s ($(( DPMS_TIMEOUT / 60 )) min)"
    echo -e "Lock command:     ${LOCK_COMMAND}"
    echo

    # Power settings
    echo -e "${BOLD}Power Settings${NC}"
    echo -e "Disable on battery: ${DISABLE_ON_BATTERY}"
    if [[ "$DISABLE_ON_BATTERY" == "true" ]]; then
        echo -e "Battery timeout:    ${BATTERY_IDLE_TIMEOUT}s"
    fi

    # Current power status
    if is_on_battery; then
        echo -e "Current power:      ${YELLOW}Battery${NC}"
    else
        echo -e "Current power:      ${GREEN}AC${NC}"
    fi
    echo

    # Animation settings
    echo -e "${BOLD}Animation${NC}"
    echo -e "Frame rate:       ${FRAME_RATE} FPS"
    if [[ -n "$INCLUDE_EFFECTS" ]]; then
        echo -e "Include effects:  ${GREEN}${INCLUDE_EFFECTS}${NC}"
        echo -e "Exclude effects:  ${YELLOW}(ignored - include is set)${NC}"
    else
        echo -e "Include effects:  ${YELLOW}(all)${NC}"
        echo -e "Exclude effects:  ${EXCLUDE_EFFECTS}"
    fi
    echo -e "Logo file:        ${LOGO_FILE}"
    echo -e "Terminal:         ${TERMINAL}"
    if [[ -n "$FADE_IN_EFFECT" ]]; then
        echo -e "Fade in:          ${GREEN}${FADE_IN_EFFECT}${NC}"
    else
        echo -e "Fade in:          ${YELLOW}(disabled)${NC}"
    fi
    if [[ -n "$FADE_OUT_EFFECT" ]]; then
        echo -e "Fade out:         ${GREEN}${FADE_OUT_EFFECT}${NC}"
    else
        echo -e "Fade out:         ${YELLOW}(disabled)${NC}"
    fi
    if [[ "$SHOW_CLOCK" == "true" ]]; then
        echo -e "Clock:            ${GREEN}enabled${NC} (${CLOCK_DURATION}s, format: ${CLOCK_FORMAT})"
        if [[ -n "$CLOCK_FONT" ]]; then
            echo -e "Clock font:       ${CLOCK_FONT}"
        fi
    else
        echo -e "Clock:            ${YELLOW}(disabled)${NC}"
    fi
    echo

    # Cursor & Input settings
    echo -e "${BOLD}Cursor & Input${NC}"
    if [[ "$CURSOR_HIDE" == "true" ]]; then
        echo -e "Hide cursor:      ${GREEN}yes${NC}"
    else
        echo -e "Hide cursor:      ${YELLOW}no${NC}"
    fi
    if [[ "$HIDE_MOUSE" == "true" ]]; then
        echo -e "Hide mouse:       ${GREEN}yes${NC}"
    else
        echo -e "Hide mouse:       ${YELLOW}no${NC}"
    fi
    if [[ "$DISMISS_ON_KEY" == "true" ]]; then
        echo -e "Dismiss on key:   ${GREEN}yes${NC}"
    else
        echo -e "Dismiss on key:   ${YELLOW}no${NC}"
    fi

    # Dependency check
    echo -e "${BOLD}Dependencies${NC}"
    if [[ "$TERMINAL" == "ghostty" ]]; then
        if command -v ghostty &>/dev/null; then
            echo -e "ghostty:          ${GREEN}installed${NC} (selected)"
        else
            echo -e "ghostty:          ${RED}not installed${NC} (selected but missing!)"
        fi
        if command -v cosmic-term &>/dev/null; then
            echo -e "cosmic-term:      ${GREEN}installed${NC} (available)"
        else
            echo -e "cosmic-term:      ${YELLOW}not installed${NC} (optional)"
        fi
    else
        if command -v cosmic-term &>/dev/null; then
            echo -e "cosmic-term:      ${GREEN}installed${NC} (selected)"
        else
            echo -e "cosmic-term:      ${RED}not installed${NC} (selected but missing!)"
        fi
        if command -v ghostty &>/dev/null; then
            echo -e "ghostty:          ${GREEN}installed${NC} (available)"
        else
            echo -e "ghostty:          ${YELLOW}not installed${NC} (optional)"
        fi
    fi
    if command -v tte &>/dev/null; then
        echo -e "tte:              ${GREEN}installed${NC} (required)"
    else
        echo -e "tte:              ${RED}not installed${NC} (required)"
    fi
    if command -v swayidle &>/dev/null; then
        echo -e "swayidle:         ${GREEN}installed${NC}"
    else
        echo -e "swayidle:         ${RED}not installed${NC}"
    fi
    if command -v wtype &>/dev/null; then
        echo -e "wtype:            ${GREEN}installed${NC} (optional, for auto-fullscreen)"
    else
        echo -e "wtype:            ${YELLOW}not installed${NC} (optional, for auto-fullscreen)"
    fi
    echo
}

# Set timer values
set_timer() {
    local timer_type="$1"
    local value="$2"

    load_config

    case "$timer_type" in
        idle)
            IDLE_TIMEOUT="$value"
            log_info "Idle timeout set to ${value}s"
            ;;
        lock)
            LOCK_TIMEOUT="$value"
            log_info "Lock timeout set to ${value}s"
            ;;
        dpms|screen)
            DPMS_TIMEOUT="$value"
            log_info "Screen off timeout set to ${value}s"
            ;;
        battery)
            BATTERY_IDLE_TIMEOUT="$value"
            log_info "Battery idle timeout set to ${value}s"
            ;;
        *)
            log_error "Unknown timer type: $timer_type"
            log_info "Valid types: idle, lock, dpms, battery"
            return 1
            ;;
    esac

    save_config
    reload_service
}

# Set power option
set_power_option() {
    local option="$1"
    local value="$2"

    load_config

    case "$option" in
        battery-disable)
            DISABLE_ON_BATTERY="$value"
            log_info "Disable on battery set to: $value"
            ;;
        *)
            log_error "Unknown power option: $option"
            return 1
            ;;
    esac

    save_config
    reload_service
}

# Set lock command
set_lock_command() {
    local command="$1"

    load_config

    if [[ -z "$command" ]]; then
        log_error "Lock command cannot be empty"
        return 1
    fi

    LOCK_COMMAND="$command"
    save_config
    reload_service

    log_info "Lock command set to: $command"
}

# Set terminal emulator
set_terminal() {
    local terminal="$1"

    load_config

    case "$terminal" in
        ghostty)
            if ! command -v ghostty &>/dev/null; then
                log_warn "Ghostty is not installed"
                log_info "Install Ghostty from: https://ghostty.org"
            fi
            TERMINAL="ghostty"
            log_info "Terminal set to: ghostty"
            ;;
        cosmic-term)
            if ! command -v cosmic-term &>/dev/null; then
                log_warn "cosmic-term is not installed"
                log_info "cosmic-term is included with COSMIC Desktop"
            fi
            TERMINAL="cosmic-term"
            log_info "Terminal set to: cosmic-term"
            ;;
        *)
            log_error "Unknown terminal: $terminal"
            log_info "Valid terminals: ghostty, cosmic-term"
            return 1
            ;;
    esac

    save_config
}

# Set fade-in effect
set_fade_in() {
    local effect="$1"

    load_config

    if [[ -z "$effect" ]] || [[ "$effect" == "none" ]] || [[ "$effect" == "off" ]]; then
        FADE_IN_EFFECT=""
        log_info "Fade-in disabled"
    else
        # Validate effect name
        if ! validate_effects "$effect"; then
            return 1
        fi
        FADE_IN_EFFECT="$effect"
        log_info "Fade-in effect set to: $effect"
    fi

    save_config
}

# Set fade-out effect
set_fade_out() {
    local effect="$1"

    load_config

    if [[ -z "$effect" ]] || [[ "$effect" == "none" ]] || [[ "$effect" == "off" ]]; then
        FADE_OUT_EFFECT=""
        log_info "Fade-out disabled"
    else
        # Validate effect name
        if ! validate_effects "$effect"; then
            return 1
        fi
        FADE_OUT_EFFECT="$effect"
        log_info "Fade-out effect set to: $effect"
    fi

    save_config
}

# Enable/disable clock display
set_clock_enabled() {
    local enabled="$1"

    load_config

    case "$enabled" in
        on|true|yes|1)
            SHOW_CLOCK="true"
            log_info "Clock display enabled"
            # Check for figlet/toilet
            if ! command -v figlet &>/dev/null && ! command -v toilet &>/dev/null; then
                log_warn "figlet/toilet not installed - clock will use plain text"
                log_info "Install with: sudo apt install figlet"
            fi
            ;;
        off|false|no|0)
            SHOW_CLOCK="false"
            log_info "Clock display disabled"
            ;;
        *)
            log_error "Invalid value: $enabled (use on/off)"
            return 1
            ;;
    esac

    save_config
}

# Set clock duration
set_clock_duration() {
    local duration="$1"

    load_config
    CLOCK_DURATION="$duration"
    save_config
    log_info "Clock duration set to: ${duration}s"
}

# Set clock format
set_clock_format() {
    local format="$1"

    load_config
    CLOCK_FORMAT="$format"
    save_config
    log_info "Clock format set to: $format"
}

# Set clock font
set_clock_font() {
    local font="$1"

    load_config

    if [[ -z "$font" ]] || [[ "$font" == "default" ]] || [[ "$font" == "none" ]]; then
        CLOCK_FONT=""
        log_info "Clock font set to default"
    else
        CLOCK_FONT="$font"
        log_info "Clock font set to: $font"
    fi

    save_config
}

# List available figlet fonts
list_clock_fonts() {
    echo
    echo -e "${BOLD}Available Clock Fonts${NC}"
    echo "─────────────────────"

    if command -v figlet &>/dev/null; then
        local figlet_dir
        figlet_dir=$(figlet -I2 2>/dev/null)
        if [[ -d "$figlet_dir" ]]; then
            echo "figlet fonts in $figlet_dir:"
            # shellcheck disable=SC2012,SC2011
            ls "$figlet_dir"/*.flf 2>/dev/null | xargs -n1 basename 2>/dev/null | sed 's/\.flf$//' | column
        fi
    else
        echo -e "${YELLOW}figlet not installed${NC}"
        echo "Install with: sudo apt install figlet"
    fi

    if command -v toilet &>/dev/null; then
        local toilet_dir="/usr/share/figlet"
        if [[ -d "$toilet_dir" ]]; then
            echo
            echo "toilet fonts in $toilet_dir:"
            # shellcheck disable=SC2012,SC2011
            ls "$toilet_dir"/*.tlf 2>/dev/null | xargs -n1 basename 2>/dev/null | sed 's/\.tlf$//' | column
        fi
    fi
    echo
}

# Get all available TTE effects (cached)
get_all_effects() {
    # Return cached result if available
    if [[ -n "$EFFECTS_CACHE" ]]; then
        echo "$EFFECTS_CACHE"
        return
    fi

    # Check if tte is available
    if ! command -v tte &>/dev/null; then
        log_error "tte (TerminalTextEffects) not installed"
        return 1
    fi

    # Parse effects from TTE help output
    # Format: {effect1,effect2,...}
    EFFECTS_CACHE=$(tte -h 2>&1 | grep -oE '\{beams,[^}]+\}' | head -1 | tr -d '{}' | tr ',' '\n' | sort)
    echo "$EFFECTS_CACHE"
}

# Validate that effect names exist
# Returns 0 if all effects are valid, 1 otherwise
validate_effects() {
    local effects_to_check="$1"
    local all_effects

    all_effects=$(get_all_effects)
    if [[ -z "$all_effects" ]]; then
        return 1
    fi

    local invalid_effects=""
    IFS=',' read -ra effect_arr <<< "$effects_to_check"
    for effect in "${effect_arr[@]}"; do
        # Trim whitespace
        effect=$(echo "$effect" | tr -d ' ')
        if [[ -z "$effect" ]]; then
            continue
        fi
        if ! echo "$all_effects" | grep -qx "$effect"; then
            if [[ -z "$invalid_effects" ]]; then
                invalid_effects="$effect"
            else
                invalid_effects="$invalid_effects, $effect"
            fi
        fi
    done

    if [[ -n "$invalid_effects" ]]; then
        log_error "Invalid effect(s): $invalid_effects"
        log_info "Use '$0 effects list' to see available effects"
        return 1
    fi
    return 0
}

# List effects with status
list_effects() {
    load_config
    local all_effects
    all_effects=$(get_all_effects)

    echo
    echo -e "${BOLD}Available Effects${NC}"
    echo "─────────────────────"

    if [[ -n "$INCLUDE_EFFECTS" ]]; then
        echo -e "Mode: ${GREEN}Include list active${NC}"
        echo
        local include_arr
        IFS=',' read -ra include_arr <<< "$INCLUDE_EFFECTS"
        for effect in $all_effects; do
            local marker=" "
            for inc in "${include_arr[@]}"; do
                if [[ "$effect" == "$inc" ]]; then
                    marker="${GREEN}✓${NC}"
                    break
                fi
            done
            echo -e "  $marker $effect"
        done
    else
        echo -e "Mode: ${YELLOW}Exclude list active${NC}"
        echo
        local exclude_arr
        IFS=',' read -ra exclude_arr <<< "$EXCLUDE_EFFECTS"
        for effect in $all_effects; do
            local marker="${GREEN}✓${NC}"
            for exc in "${exclude_arr[@]}"; do
                if [[ "$effect" == "$exc" ]]; then
                    marker="${RED}✗${NC}"
                    break
                fi
            done
            echo -e "  $marker $effect"
        done
    fi
    echo
}

# Set include effects list
set_include_effects() {
    local effects="$1"

    load_config

    # Validate effects if not empty
    if [[ -n "$effects" ]]; then
        if ! validate_effects "$effects"; then
            return 1
        fi
    fi

    INCLUDE_EFFECTS="$effects"
    save_config

    if [[ -n "$effects" ]]; then
        log_info "Include effects set to: $effects"
        log_info "Exclude effects will be ignored"
    else
        log_info "Include effects cleared (using exclude list)"
    fi
}

# Set exclude effects list
set_exclude_effects() {
    local effects="$1"

    load_config

    # Validate effects if not empty
    if [[ -n "$effects" ]]; then
        if ! validate_effects "$effects"; then
            return 1
        fi
    fi

    EXCLUDE_EFFECTS="$effects"
    save_config

    log_info "Exclude effects set to: $effects"
    if [[ -n "$INCLUDE_EFFECTS" ]]; then
        log_warn "Note: Include effects is set, exclude will be ignored"
    fi
}

# Add effects to include list
add_include_effects() {
    local new_effects="$1"

    load_config

    # Validate effects before adding
    if ! validate_effects "$new_effects"; then
        return 1
    fi

    if [[ -z "$INCLUDE_EFFECTS" ]]; then
        INCLUDE_EFFECTS="$new_effects"
    else
        INCLUDE_EFFECTS="${INCLUDE_EFFECTS},${new_effects}"
    fi
    save_config

    log_info "Added to include list: $new_effects"
}

# Add effects to exclude list
add_exclude_effects() {
    local new_effects="$1"

    load_config

    # Validate effects before adding
    if ! validate_effects "$new_effects"; then
        return 1
    fi

    if [[ -z "$EXCLUDE_EFFECTS" ]]; then
        EXCLUDE_EFFECTS="$new_effects"
    else
        EXCLUDE_EFFECTS="${EXCLUDE_EFFECTS},${new_effects}"
    fi
    save_config

    log_info "Added to exclude list: $new_effects"
}

# Clear effects lists
clear_effects() {
    local list="${1:-both}"

    load_config

    case "$list" in
        include)
            INCLUDE_EFFECTS=""
            log_info "Include effects cleared"
            ;;
        exclude)
            EXCLUDE_EFFECTS=""
            log_info "Exclude effects cleared"
            ;;
        both|all)
            INCLUDE_EFFECTS=""
            EXCLUDE_EFFECTS=""
            log_info "All effects lists cleared"
            ;;
    esac

    save_config
}

# List available logos
list_logos() {
    local logos_dir="${SCRIPT_DIR}/logos"
    echo
    echo -e "${BOLD}Available Logos${NC}"
    echo "────────────────"

    if [[ -d "$logos_dir" ]]; then
        local i=1
        for logo in "$logos_dir"/*.txt; do
            if [[ -f "$logo" ]]; then
                local name
                name=$(basename "$logo" .txt)
                local current=""
                if [[ "$(readlink -f "$LOGO_FILE" 2>/dev/null)" == "$(readlink -f "$logo")" ]] || \
                   diff -q "$LOGO_FILE" "$logo" &>/dev/null 2>&1; then
                    current=" ${GREEN}(current)${NC}"
                fi
                echo -e "  $i) $name$current"
                ((i++))
            fi
        done
    else
        log_warn "Logos directory not found: $logos_dir"
    fi
    echo
}

# Set logo
set_logo() {
    local selection="$1"
    local logos_dir="${SCRIPT_DIR}/logos"

    # Check if selection is a number or a name
    if [[ "$selection" =~ ^[0-9]+$ ]]; then
        # Selection by number
        local logos=("$logos_dir"/*.txt)
        local index=$((selection - 1))
        if [[ $index -ge 0 ]] && [[ $index -lt ${#logos[@]} ]]; then
            local logo_path="${logos[$index]}"
            cp "$logo_path" "$SCREENSAVER_DIR/logo.txt"
            LOGO_FILE="$SCREENSAVER_DIR/logo.txt"
            save_config
            log_success "Logo set to: $(basename "$logo_path" .txt)"
        else
            log_error "Invalid selection: $selection"
            return 1
        fi
    else
        # Selection by name
        local logo_path="$logos_dir/${selection}.txt"
        if [[ -f "$logo_path" ]]; then
            cp "$logo_path" "$SCREENSAVER_DIR/logo.txt"
            LOGO_FILE="$SCREENSAVER_DIR/logo.txt"
            save_config
            log_success "Logo set to: $selection"
        else
            log_error "Logo not found: $selection"
            log_info "Available logos:"
            list_logos
            return 1
        fi
    fi
}

# Preview a logo
preview_logo() {
    local selection="$1"
    local logos_dir="${SCRIPT_DIR}/logos"
    local logo_path

    if [[ "$selection" =~ ^[0-9]+$ ]]; then
        local logos=("$logos_dir"/*.txt)
        local index=$((selection - 1))
        logo_path="${logos[$index]}"
    else
        logo_path="$logos_dir/${selection}.txt"
    fi

    if [[ -f "$logo_path" ]]; then
        echo
        echo -e "${BOLD}Preview: $(basename "$logo_path" .txt)${NC}"
        echo "────────────────────────────────────"
        cat "$logo_path"
        echo "────────────────────────────────────"
    else
        log_error "Logo not found"
    fi
}

# Interactive configuration menu
interactive_menu() {
    load_config

    while true; do
        echo
        echo -e "${BOLD}COSMIC Screensaver Configuration${NC}"
        echo "─────────────────────────────────────"
        echo "1) Show status"
        echo "2) Enable screensaver"
        echo "3) Disable screensaver"
        echo "4) Set idle timeout"
        echo "5) Set lock timeout"
        echo "6) Set screen off timeout"
        echo "7) Configure power settings"
        echo "8) Change logo"
        echo "9) Change terminal"
        echo "t) Test screensaver"
        echo "i) Install dependencies"
        echo "0) Exit"
        echo
        read -r -p "Select option: " choice

        case "$choice" in
            1) show_status ;;
            2) enable_service ;;
            3) disable_service ;;
            4)
                read -r -p "Idle timeout (seconds) [${IDLE_TIMEOUT}]: " value
                [[ -n "$value" ]] && set_timer idle "$value"
                ;;
            5)
                read -r -p "Lock timeout (seconds, 0 to disable) [${LOCK_TIMEOUT}]: " value
                [[ -n "$value" ]] && set_timer lock "$value"
                ;;
            6)
                read -r -p "Screen off timeout (seconds, 0 to disable) [${DPMS_TIMEOUT}]: " value
                [[ -n "$value" ]] && set_timer dpms "$value"
                ;;
            7)
                echo
                echo "Power Settings:"
                echo "1) Disable screensaver on battery: $DISABLE_ON_BATTERY"
                echo "2) Battery idle timeout: ${BATTERY_IDLE_TIMEOUT}s"
                read -r -p "Select option: " power_choice
                case "$power_choice" in
                    1)
                        if [[ "$DISABLE_ON_BATTERY" == "true" ]]; then
                            set_power_option battery-disable false
                        else
                            set_power_option battery-disable true
                        fi
                        ;;
                    2)
                        read -r -p "Battery idle timeout (seconds): " value
                        [[ -n "$value" ]] && set_timer battery "$value"
                        ;;
                esac
                ;;
            8)
                list_logos
                read -r -p "Select logo (number or name), or 'p' to preview: " logo_choice
                if [[ "$logo_choice" == "p" ]]; then
                    read -r -p "Logo to preview: " preview_choice
                    preview_logo "$preview_choice"
                elif [[ -n "$logo_choice" ]]; then
                    set_logo "$logo_choice"
                fi
                ;;
            9)
                echo
                echo "Terminal Emulators:"
                echo "1) ghostty $(if [[ "$TERMINAL" == "ghostty" ]]; then echo "(current)"; fi)"
                echo "2) cosmic-term $(if [[ "$TERMINAL" == "cosmic-term" ]]; then echo "(current)"; fi)"
                read -r -p "Select terminal: " term_choice
                case "$term_choice" in
                    1) set_terminal ghostty ;;
                    2) set_terminal cosmic-term ;;
                    *) log_error "Invalid option" ;;
                esac
                ;;
            t|T)
                log_info "Starting screensaver test (press any key to exit)..."
                "$SCREENSAVER_SCRIPT" test
                ;;
            i|I)
                install_dependencies
                ;;
            0) exit 0 ;;
            *) log_error "Invalid option" ;;
        esac
    done
}

# Install dependencies
install_dependencies() {
    echo
    log_info "Installing dependencies..."

    # Check for Ghostty (required)
    if ! command -v ghostty &>/dev/null; then
        log_error "Ghostty is required but not installed"
        log_info "Install Ghostty from: https://ghostty.org"
        log_info "  - Flatpak: flatpak install flathub com.mitchellh.ghostty"
        log_info "  - Or build from source: https://github.com/ghostty-org/ghostty"
        return 1
    fi
    log_success "Ghostty is installed"

    # Check for pipx/pip
    if command -v pipx &>/dev/null; then
        log_info "Installing TerminalTextEffects with pipx..."
        pipx install terminaltexteffects
    elif command -v pip &>/dev/null; then
        log_info "Installing TerminalTextEffects with pip..."
        pip install --user terminaltexteffects
    else
        log_error "Neither pipx nor pip found. Install Python first."
        return 1
    fi

    # Check for swayidle
    if ! command -v swayidle &>/dev/null; then
        log_info "Installing swayidle..."
        if command -v apt &>/dev/null; then
            sudo apt install -y swayidle
        else
            log_warn "Please install swayidle manually for your distribution"
        fi
    fi

    # Check for wtype (optional, for auto-fullscreen on COSMIC)
    if ! command -v wtype &>/dev/null; then
        log_info "Installing wtype (for auto-fullscreen support)..."
        if command -v apt &>/dev/null; then
            sudo apt install -y wtype
        else
            log_warn "Please install wtype manually for auto-fullscreen support"
        fi
    fi

    log_success "Dependencies installed"
}

# Initial setup
setup() {
    ensure_dirs

    # Copy default logo if none exists
    if [[ ! -f "$SCREENSAVER_DIR/logo.txt" ]]; then
        local default_logo="${SCRIPT_DIR}/logos/pop-os-name-with-icon.txt"
        if [[ -f "$default_logo" ]]; then
            cp "$default_logo" "$SCREENSAVER_DIR/logo.txt"
            log_info "Copied default logo (pop-os-name-with-icon)"
        else
            # Fallback: use first available logo
            local first_logo
            first_logo=$(find "${SCRIPT_DIR}/logos" -name "*.txt" -type f | head -1)
            if [[ -n "$first_logo" ]]; then
                cp "$first_logo" "$SCREENSAVER_DIR/logo.txt"
                log_info "Copied default logo ($(basename "$first_logo" .txt))"
            fi
        fi
    fi

    # Symlink launcher script
    if [[ ! -f "$SCREENSAVER_DIR/run-screensaver.sh" ]] && [[ -f "${SCRIPT_DIR}/run-screensaver.sh" ]]; then
        ln -sf "${SCRIPT_DIR}/run-screensaver.sh" "$SCREENSAVER_DIR/run-screensaver.sh"
        log_info "Linked launcher script"
    fi

    # Symlink main screensaver script
    if [[ ! -f "$SCREENSAVER_DIR/cosmic-screensaver.sh" ]]; then
        ln -sf "${SCRIPT_DIR}/cosmic-screensaver.sh" "$SCREENSAVER_DIR/cosmic-screensaver.sh"
        log_info "Linked screensaver script"
    fi

    # Symlink screensaver-ctl to ~/.local/bin for PATH access
    local local_bin="$HOME/.local/bin"
    mkdir -p "$local_bin"
    if [[ ! -L "$local_bin/screensaver-ctl" ]] || [[ "$(readlink -f "$local_bin/screensaver-ctl")" != "$(readlink -f "${SCRIPT_DIR}/screensaver-ctl.sh")" ]]; then
        ln -sf "${SCRIPT_DIR}/screensaver-ctl.sh" "$local_bin/screensaver-ctl"
        log_info "Linked screensaver-ctl to ~/.local/bin"
    fi

    load_config
    save_config
    log_success "Initial setup complete"
    echo
    log_info "Next steps:"
    echo "  1. Run: $0 install  - to install dependencies"
    echo "  2. Run: $0 enable   - to enable the screensaver"
    echo "  3. Run: $0 test     - to test the screensaver"
    echo
    log_info "You can now run 'screensaver-ctl' from anywhere (if ~/.local/bin is in PATH)"
}

# Add COSMIC keyboard shortcut
add_shortcut() {
    local system_actions="$HOME/.config/cosmic/com.system76.CosmicSettings.Shortcuts/v1/system_actions"
    local defaults="$HOME/.config/cosmic/com.system76.CosmicSettings.Shortcuts/v1/defaults"
    local launcher_path="${FULLSCREEN_LAUNCHER}"
    local escaped_path="${launcher_path//\//\\/}"

    if [[ ! -f "$system_actions" ]] || [[ ! -f "$defaults" ]]; then
        log_error "COSMIC shortcuts config not found"
        log_info "Please configure COSMIC shortcuts manually"
        return 1
    fi

    # Check if screensaver already exists and update if needed
    if grep -q "Screensaver:" "$system_actions" 2>/dev/null; then
        # Update existing shortcut to use fullscreen launcher
        if grep -q "cosmic-term" "$system_actions" 2>/dev/null; then
            cp "$system_actions" "${system_actions}.backup"
            sed -i "s|Screensaver: \"cosmic-term.*\"|Screensaver: \"${launcher_path} launch\"|" "$system_actions"
            log_success "Updated Screensaver to use fullscreen launcher"
        else
            log_info "Screensaver shortcut already configured for fullscreen"
        fi
    else
        # Backup original
        cp "$system_actions" "${system_actions}.backup"

        # Add screensaver action before closing brace
        sed -i "s|}$|    /// Launches the terminal screensaver (fullscreen)\n    Screensaver: \"${escaped_path} launch\",\n}|" "$system_actions"

        log_success "Added Screensaver to system_actions"
    fi

    # Check if keybinding already exists
    if grep -q "System(Screensaver)" "$defaults" 2>/dev/null; then
        log_warn "Screensaver keybinding already exists"
    else
        # Backup original
        cp "$defaults" "${defaults}.backup"

        # Add keybinding before closing brace
        sed -i 's/}$/\n    \/\/ Screensaver: Super+Shift+Z\n    (modifiers: [Super, Shift], key: "z"): System(Screensaver),\n}/' "$defaults"

        log_success "Added Super+Shift+Z keybinding"
    fi

    echo
    log_info "Changes applied. Please log out and back in for shortcuts to take effect."
    log_info "Backups saved as *.backup files"
}

# Show usage
usage() {
    cat << EOF
Usage: $(basename "$0") [COMMAND] [OPTIONS]

Management script for COSMIC Screensaver.

Commands:
    status          Show current status and configuration
    enable          Enable screensaver with swayidle
    disable         Disable screensaver service
    reload          Reload configuration
    setup           Initial setup (create config directory)
    install         Install dependencies (tte, swayidle)
    test [EFFECT]   Test the screensaver (optionally with specific effect)
    menu            Interactive configuration menu

Timer Commands:
    set idle SECONDS        Set idle timeout before screensaver
    set lock SECONDS        Set lock timeout (0 to disable)
    set dpms SECONDS        Set screen off timeout (0 to disable)
    set battery SECONDS     Set battery idle timeout
    set terminal NAME       Set terminal emulator (ghostty, cosmic-term)
    set lock-command CMD    Set lock screen command (default: cosmic-greeter --lock)

Power Commands:
    power battery on        Disable screensaver on battery
    power battery off       Keep screensaver on battery

Effects Commands:
    effects list            List all effects with include/exclude status
    effects include E1,E2   Set effects to include (use only these)
    effects exclude E1,E2   Set effects to exclude
    effects add-include E   Add effect(s) to include list
    effects add-exclude E   Add effect(s) to exclude list
    effects clear [list]    Clear include, exclude, or both lists

Fade Transition Commands:
    fade in EFFECT          Set fade-in effect (expand, slide, middleout, etc.)
    fade out EFFECT         Set fade-out effect (burn, crumble, scattered, etc.)
    fade in off             Disable fade-in
    fade out off            Disable fade-out

Clock Commands:
    clock on                Enable clock display between effects
    clock off               Disable clock display
    clock duration SECS     Set clock display duration (default: 3)
    clock format FMT        Set time format (default: %H:%M)
    clock font NAME         Set figlet/toilet font (or 'default')
    clock fonts             List available fonts

Logo Commands:
    logos                   List available logos
    logo NAME               Set logo by name (e.g., pop-os, framework)
    logo NUMBER             Set logo by number from list
    preview NAME            Preview a logo without setting it

Shortcut Commands:
    add-shortcut            Add COSMIC keyboard shortcut (Super+Shift+Z)

Examples:
    $(basename "$0") enable                 # Enable screensaver
    $(basename "$0") set idle 300           # Start after 5 min idle
    $(basename "$0") set lock 0             # Disable auto-lock
    $(basename "$0") set terminal cosmic-term   # Use cosmic-term
    $(basename "$0") effects list           # Show all effects
    $(basename "$0") effects include matrix,blackhole,burn  # Use only these
    $(basename "$0") fade in expand         # Fade in with expand effect
    $(basename "$0") fade out burn          # Fade out with burn effect
    $(basename "$0") clock on               # Show clock between effects
    $(basename "$0") clock format '%H:%M:%S'  # Show seconds too
    $(basename "$0") power battery on       # Skip screensaver on battery
    $(basename "$0") logo framework         # Use Framework logo
    $(basename "$0") test                   # Preview screensaver
    $(basename "$0") test blackhole         # Test with blackhole effect

EOF
}

# Main entry point
main() {
    local command="${1:-menu}"
    shift 2>/dev/null || true

    case "$command" in
        status)
            show_status
            ;;
        enable)
            enable_service
            ;;
        disable)
            disable_service
            ;;
        reload)
            reload_service
            ;;
        setup)
            setup
            ;;
        install)
            install_dependencies
            ;;
        test)
            "$SCREENSAVER_SCRIPT" test "$@"
            ;;
        set)
            local option_type="${1:-}"
            local value="${2:-}"
            if [[ -z "$option_type" ]] || [[ -z "$value" ]]; then
                log_error "Usage: $0 set <idle|lock|dpms|battery|terminal|lock-command> VALUE"
                exit 1
            fi
            case "$option_type" in
                terminal)
                    set_terminal "$value"
                    ;;
                lock-command)
                    set_lock_command "$value"
                    ;;
                *)
                    set_timer "$option_type" "$value"
                    ;;
            esac
            ;;
        power)
            local option="${1:-}"
            local value="${2:-}"
            case "$option" in
                battery)
                    if [[ "$value" == "on" ]]; then
                        set_power_option battery-disable true
                    else
                        set_power_option battery-disable false
                    fi
                    ;;
                *)
                    log_error "Usage: $0 power battery <on|off>"
                    exit 1
                    ;;
            esac
            ;;
        menu)
            interactive_menu
            ;;
        effects)
            local subcmd="${1:-list}"
            shift 2>/dev/null || true
            case "$subcmd" in
                list)
                    list_effects
                    ;;
                include)
                    local effects="${1:-}"
                    if [[ -z "$effects" ]]; then
                        log_error "Usage: $0 effects include EFFECT1,EFFECT2,..."
                        exit 1
                    fi
                    set_include_effects "$effects"
                    ;;
                exclude)
                    local effects="${1:-}"
                    if [[ -z "$effects" ]]; then
                        log_error "Usage: $0 effects exclude EFFECT1,EFFECT2,..."
                        exit 1
                    fi
                    set_exclude_effects "$effects"
                    ;;
                add-include)
                    local effects="${1:-}"
                    if [[ -z "$effects" ]]; then
                        log_error "Usage: $0 effects add-include EFFECT1,EFFECT2,..."
                        exit 1
                    fi
                    add_include_effects "$effects"
                    ;;
                add-exclude)
                    local effects="${1:-}"
                    if [[ -z "$effects" ]]; then
                        log_error "Usage: $0 effects add-exclude EFFECT1,EFFECT2,..."
                        exit 1
                    fi
                    add_exclude_effects "$effects"
                    ;;
                clear)
                    local list="${1:-both}"
                    clear_effects "$list"
                    ;;
                *)
                    log_error "Unknown effects subcommand: $subcmd"
                    log_info "Usage: $0 effects <list|include|exclude|add-include|add-exclude|clear>"
                    exit 1
                    ;;
            esac
            ;;
        fade)
            local direction="${1:-}"
            local effect="${2:-}"
            if [[ -z "$direction" ]]; then
                log_error "Usage: $0 fade <in|out> <EFFECT|off>"
                exit 1
            fi
            case "$direction" in
                in)
                    if [[ -z "$effect" ]]; then
                        log_error "Usage: $0 fade in <EFFECT|off>"
                        exit 1
                    fi
                    set_fade_in "$effect"
                    ;;
                out)
                    if [[ -z "$effect" ]]; then
                        log_error "Usage: $0 fade out <EFFECT|off>"
                        exit 1
                    fi
                    set_fade_out "$effect"
                    ;;
                *)
                    log_error "Unknown fade direction: $direction"
                    log_info "Usage: $0 fade <in|out> <EFFECT|off>"
                    exit 1
                    ;;
            esac
            ;;
        clock)
            local subcmd="${1:-}"
            local value="${2:-}"
            if [[ -z "$subcmd" ]]; then
                log_error "Usage: $0 clock <on|off|duration|format|font|fonts>"
                exit 1
            fi
            case "$subcmd" in
                on|off|true|false)
                    set_clock_enabled "$subcmd"
                    ;;
                duration)
                    if [[ -z "$value" ]]; then
                        log_error "Usage: $0 clock duration SECONDS"
                        exit 1
                    fi
                    set_clock_duration "$value"
                    ;;
                format)
                    if [[ -z "$value" ]]; then
                        log_error "Usage: $0 clock format FORMAT"
                        exit 1
                    fi
                    set_clock_format "$value"
                    ;;
                font)
                    set_clock_font "${value:-default}"
                    ;;
                fonts|list-fonts)
                    list_clock_fonts
                    ;;
                *)
                    log_error "Unknown clock subcommand: $subcmd"
                    log_info "Usage: $0 clock <on|off|duration|format|font|fonts>"
                    exit 1
                    ;;
            esac
            ;;
        logos|list-logos)
            load_config
            list_logos
            ;;
        logo)
            load_config
            local selection="${1:-}"
            if [[ -z "$selection" ]]; then
                log_error "Usage: $0 logo <name|number>"
                list_logos
                exit 1
            fi
            set_logo "$selection"
            ;;
        preview)
            load_config
            local selection="${1:-}"
            if [[ -z "$selection" ]]; then
                log_error "Usage: $0 preview <name|number>"
                exit 1
            fi
            preview_logo "$selection"
            ;;
        add-shortcut)
            setup
            add_shortcut
            ;;
        help|-h|--help)
            usage
            ;;
        *)
            log_error "Unknown command: $command"
            usage
            exit 1
            ;;
    esac
}

main "$@"
