// SPDX-License-Identifier: GPL-3.0-only

//! btop theme generator
//!
//! Generates a btop theme file from the COSMIC color palette
//! and activates it in the user's btop config.

use std::path::PathBuf;

use crate::colors::ColorPalette;

/// Generate btop theme file content from a color palette
pub fn generate_theme(palette: &ColorPalette) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str("# COSMIC theme for btop\n");
    out.push_str("# Auto-generated by COSMIC ORDER\n\n");

    // Main colors
    out.push_str(&format!("theme[main_bg]=\"{}\"\n", palette.background));
    out.push_str(&format!("theme[main_fg]=\"{}\"\n", palette.foreground));
    out.push_str(&format!("theme[title]=\"{}\"\n", palette.foreground));
    out.push_str(&format!("theme[hi_fg]=\"{}\"\n", palette.accent));
    out.push_str(&format!(
        "theme[selected_bg]=\"{}\"\n",
        palette.selection_background
    ));
    out.push_str(&format!(
        "theme[selected_fg]=\"{}\"\n",
        palette.selection_foreground
    ));
    out.push_str(&format!("theme[inactive_fg]=\"{}\"\n", palette.colors[8])); // bright black
    out.push_str(&format!("theme[graph_text]=\"{}\"\n", palette.colors[7])); // white
    out.push_str(&format!("theme[proc_misc]=\"{}\"\n", palette.colors[2])); // green

    // Box outline colors (accent)
    out.push_str(&format!("theme[cpu_box]=\"{}\"\n", palette.accent));
    out.push_str(&format!("theme[mem_box]=\"{}\"\n", palette.accent));
    out.push_str(&format!("theme[net_box]=\"{}\"\n", palette.accent));
    out.push_str(&format!("theme[proc_box]=\"{}\"\n", palette.accent));
    out.push_str(&format!("theme[div_line]=\"{}\"\n", palette.colors[8])); // bright black

    // Temperature gradient: blue → yellow → red
    out.push_str(&format!("theme[temp_start]=\"{}\"\n", palette.colors[4])); // blue
    out.push_str(&format!("theme[temp_mid]=\"{}\"\n", palette.colors[3])); // yellow
    out.push_str(&format!("theme[temp_end]=\"{}\"\n", palette.colors[1])); // red

    // CPU gradient: green → cyan → red
    out.push_str(&format!("theme[cpu_start]=\"{}\"\n", palette.colors[2])); // green
    out.push_str(&format!("theme[cpu_mid]=\"{}\"\n", palette.accent)); // accent/cyan
    out.push_str(&format!("theme[cpu_end]=\"{}\"\n", palette.colors[1])); // red

    // Free meter: dark → green
    out.push_str(&format!("theme[free_start]=\"{}\"\n", palette.colors[8])); // bright black
    out.push_str(&format!("theme[free_mid]=\"{}\"\n", palette.colors[2])); // green
    out.push_str(&format!("theme[free_end]=\"{}\"\n", palette.colors[10])); // bright green

    // Cached meter: dark → cyan
    out.push_str(&format!("theme[cached_start]=\"{}\"\n", palette.colors[8]));
    out.push_str(&format!("theme[cached_mid]=\"{}\"\n", palette.accent));
    out.push_str(&format!("theme[cached_end]=\"{}\"\n", palette.colors[14])); // bright cyan

    // Available meter: dark → yellow
    out.push_str(&format!(
        "theme[available_start]=\"{}\"\n",
        palette.colors[8]
    ));
    out.push_str(&format!("theme[available_mid]=\"{}\"\n", palette.colors[3])); // yellow
    out.push_str(&format!(
        "theme[available_end]=\"{}\"\n",
        palette.colors[11]
    )); // bright yellow

    // Used meter: dark → red
    out.push_str(&format!("theme[used_start]=\"{}\"\n", palette.colors[8]));
    out.push_str(&format!("theme[used_mid]=\"{}\"\n", palette.colors[1])); // red
    out.push_str(&format!("theme[used_end]=\"{}\"\n", palette.colors[9])); // bright red

    // Download gradient: dark → magenta
    out.push_str(&format!(
        "theme[download_start]=\"{}\"\n",
        palette.colors[0]
    )); // black
    out.push_str(&format!("theme[download_mid]=\"{}\"\n", palette.colors[5])); // magenta
    out.push_str(&format!("theme[download_end]=\"{}\"\n", palette.colors[13])); // bright magenta

    // Upload gradient: dark → blue
    out.push_str(&format!("theme[upload_start]=\"{}\"\n", palette.colors[0]));
    out.push_str(&format!("theme[upload_mid]=\"{}\"\n", palette.colors[4])); // blue
    out.push_str(&format!("theme[upload_end]=\"{}\"\n", palette.colors[12])); // bright blue

    out
}

/// Write the generated theme to `~/.config/btop/themes/cosmic-synced.theme`
pub async fn write_theme(palette: &ColorPalette) -> Result<PathBuf, std::io::Error> {
    let themes_dir = btop_themes_dir();
    tokio::fs::create_dir_all(&themes_dir).await?;
    let path = themes_dir.join("cosmic-synced.theme");
    tokio::fs::write(&path, generate_theme(palette)).await?;
    Ok(path)
}

/// Activate the `cosmic-synced` theme in `~/.config/btop/btop.conf`
pub async fn activate_theme() -> Result<(), std::io::Error> {
    let config_path = btop_config_path();

    if let Some(parent) = config_path.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }

    let contents = match tokio::fs::read_to_string(&config_path).await {
        Ok(c) => c,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(e),
    };

    let theme_line = "color_theme = \"cosmic-synced\"";
    let mut found = false;
    let mut new_lines: Vec<String> = Vec::new();

    for line in contents.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("color_theme") && trimmed.contains('=') {
            new_lines.push(theme_line.to_string());
            found = true;
        } else {
            new_lines.push(line.to_string());
        }
    }

    if !found {
        if !new_lines.is_empty() && new_lines.last().is_some_and(|l| !l.is_empty()) {
            new_lines.push(String::new());
        }
        new_lines.push(theme_line.to_string());
    }

    new_lines.push(String::new());

    tokio::fs::write(&config_path, new_lines.join("\n")).await?;
    Ok(())
}

fn btop_config_path() -> PathBuf {
    directories::BaseDirs::new()
        .map(|d| d.config_dir().join("btop").join("btop.conf"))
        .unwrap_or_else(|| {
            let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
            PathBuf::from(home).join(".config/btop/btop.conf")
        })
}

fn btop_themes_dir() -> PathBuf {
    directories::BaseDirs::new()
        .map(|d| d.config_dir().join("btop").join("themes"))
        .unwrap_or_else(|| {
            let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
            PathBuf::from(home).join(".config/btop/themes")
        })
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    fn sample_palette() -> ColorPalette {
        ColorPalette {
            accent: "#63D1D6".to_string(),
            cursor: "#FFFFFF".to_string(),
            foreground: "#FFFFFF".to_string(),
            background: "#1B1B1B".to_string(),
            selection_foreground: "#1B1B1B".to_string(),
            selection_background: "#FFFFFF".to_string(),
            colors: [
                "#3B3B3B".to_string(),
                "#FF6B6B".to_string(),
                "#87D687".to_string(),
                "#FFD93D".to_string(),
                "#6B9FFF".to_string(),
                "#B87DFF".to_string(),
                "#63D1D6".to_string(),
                "#D4D4D4".to_string(),
                "#5A5A5A".to_string(),
                "#FF6B6B".to_string(),
                "#87D687".to_string(),
                "#FFD93D".to_string(),
                "#6B9FFF".to_string(),
                "#B87DFF".to_string(),
                "#63D1D6".to_string(),
                "#E8E8E8".to_string(),
            ],
        }
    }

    #[test]
    fn test_generate_theme_format() {
        let palette = sample_palette();
        let theme = generate_theme(&palette);

        // Verify btop format: theme[key]="hex"
        assert!(theme.contains("theme[main_bg]=\"#1B1B1B\""));
        assert!(theme.contains("theme[main_fg]=\"#FFFFFF\""));
        assert!(theme.contains("theme[hi_fg]=\"#63D1D6\""));
        assert!(theme.contains("theme[cpu_start]=\"#87D687\""));
        assert!(theme.contains("theme[cpu_end]=\"#FF6B6B\""));
    }

    #[test]
    fn test_generate_theme_key_count() {
        let palette = sample_palette();
        let theme = generate_theme(&palette);

        let key_lines: Vec<&str> = theme.lines().filter(|l| l.starts_with("theme[")).collect();
        // 14 main + 24 gradient (8 gradients × 3 each) = 38 keys
        assert_eq!(key_lines.len(), 38);
    }
}
