// SPDX-License-Identifier: GPL-3.0-only

//! btop theme generator
//!
//! Generates a btop theme file from the COSMIC color palette
//! and activates it in the user's btop config.

use std::fmt::Write;
use std::path::PathBuf;

use crate::colors::ColorPalette;
use crate::paths;

/// Generate btop theme file content from a color palette
pub fn generate_theme(palette: &ColorPalette) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str("# COSMIC theme for btop\n");
    out.push_str("# Auto-generated by COSMIC ORDER\n\n");

    // Main colors
    let _ = writeln!(out, "theme[main_bg]=\"{}\"", palette.background);
    let _ = writeln!(out, "theme[main_fg]=\"{}\"", palette.foreground);
    let _ = writeln!(out, "theme[title]=\"{}\"", palette.foreground);
    let _ = writeln!(out, "theme[hi_fg]=\"{}\"", palette.accent);
    let _ = writeln!(
        out,
        "theme[selected_bg]=\"{}\"",
        palette.selection_background
    );
    let _ = writeln!(
        out,
        "theme[selected_fg]=\"{}\"",
        palette.selection_foreground
    );
    let _ = writeln!(out, "theme[inactive_fg]=\"{}\"", palette.colors[8]); // bright black
    let _ = writeln!(out, "theme[graph_text]=\"{}\"", palette.colors[7]); // white
    let _ = writeln!(out, "theme[proc_misc]=\"{}\"", palette.colors[2]); // green

    // Box outline colors (accent)
    let _ = writeln!(out, "theme[cpu_box]=\"{}\"", palette.accent);
    let _ = writeln!(out, "theme[mem_box]=\"{}\"", palette.accent);
    let _ = writeln!(out, "theme[net_box]=\"{}\"", palette.accent);
    let _ = writeln!(out, "theme[proc_box]=\"{}\"", palette.accent);
    let _ = writeln!(out, "theme[div_line]=\"{}\"", palette.colors[8]); // bright black

    // Temperature gradient: blue → yellow → red
    let _ = writeln!(out, "theme[temp_start]=\"{}\"", palette.colors[4]); // blue
    let _ = writeln!(out, "theme[temp_mid]=\"{}\"", palette.colors[3]); // yellow
    let _ = writeln!(out, "theme[temp_end]=\"{}\"", palette.colors[1]); // red

    // CPU gradient: green → cyan → red
    let _ = writeln!(out, "theme[cpu_start]=\"{}\"", palette.colors[2]); // green
    let _ = writeln!(out, "theme[cpu_mid]=\"{}\"", palette.accent); // accent/cyan
    let _ = writeln!(out, "theme[cpu_end]=\"{}\"", palette.colors[1]); // red

    // Free meter: dark → green
    let _ = writeln!(out, "theme[free_start]=\"{}\"", palette.colors[8]); // bright black
    let _ = writeln!(out, "theme[free_mid]=\"{}\"", palette.colors[2]); // green
    let _ = writeln!(out, "theme[free_end]=\"{}\"", palette.colors[10]); // bright green

    // Cached meter: dark → cyan
    let _ = writeln!(out, "theme[cached_start]=\"{}\"", palette.colors[8]);
    let _ = writeln!(out, "theme[cached_mid]=\"{}\"", palette.accent);
    let _ = writeln!(out, "theme[cached_end]=\"{}\"", palette.colors[14]); // bright cyan

    // Available meter: dark → yellow
    let _ = writeln!(out, "theme[available_start]=\"{}\"", palette.colors[8]);
    let _ = writeln!(out, "theme[available_mid]=\"{}\"", palette.colors[3]); // yellow
    let _ = writeln!(out, "theme[available_end]=\"{}\"", palette.colors[11]); // bright yellow

    // Used meter: dark → red
    let _ = writeln!(out, "theme[used_start]=\"{}\"", palette.colors[8]);
    let _ = writeln!(out, "theme[used_mid]=\"{}\"", palette.colors[1]); // red
    let _ = writeln!(out, "theme[used_end]=\"{}\"", palette.colors[9]); // bright red

    // Download gradient: dark → magenta
    let _ = writeln!(out, "theme[download_start]=\"{}\"", palette.colors[0]); // black
    let _ = writeln!(out, "theme[download_mid]=\"{}\"", palette.colors[5]); // magenta
    let _ = writeln!(out, "theme[download_end]=\"{}\"", palette.colors[13]); // bright magenta

    // Upload gradient: dark → blue
    let _ = writeln!(out, "theme[upload_start]=\"{}\"", palette.colors[0]);
    let _ = writeln!(out, "theme[upload_mid]=\"{}\"", palette.colors[4]); // blue
    let _ = writeln!(out, "theme[upload_end]=\"{}\"", palette.colors[12]); // bright blue

    out
}

/// Write the generated theme to `~/.config/btop/themes/cosmic-synced.theme`
pub async fn write_theme(palette: &ColorPalette) -> Result<PathBuf, std::io::Error> {
    let themes_dir = paths::btop_themes_dir();
    tokio::fs::create_dir_all(&themes_dir).await?;
    let path = themes_dir.join("cosmic-synced.theme");
    tokio::fs::write(&path, generate_theme(palette)).await?;
    Ok(path)
}

/// Activate the `cosmic-synced` theme in `~/.config/btop/btop.conf`
pub async fn activate_theme() -> Result<(), std::io::Error> {
    let config_path = paths::btop_config();

    if let Some(parent) = config_path.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }

    let contents = match tokio::fs::read_to_string(&config_path).await {
        Ok(c) => c,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(e),
    };

    let theme_line = "color_theme = \"cosmic-synced\"";
    let mut found = false;
    let mut new_lines: Vec<String> = Vec::new();

    for line in contents.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("color_theme") && trimmed.contains('=') {
            new_lines.push(theme_line.to_string());
            found = true;
        } else {
            new_lines.push(line.to_string());
        }
    }

    if !found {
        if !new_lines.is_empty() && new_lines.last().is_some_and(|l| !l.is_empty()) {
            new_lines.push(String::new());
        }
        new_lines.push(theme_line.to_string());
    }

    new_lines.push(String::new());

    tokio::fs::write(&config_path, new_lines.join("\n")).await?;
    Ok(())
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_theme_format() {
        let palette = ColorPalette::sample();
        let theme = generate_theme(&palette);

        // Verify btop format: theme[key]="hex"
        assert!(theme.contains("theme[main_bg]=\"#1B1B1B\""));
        assert!(theme.contains("theme[main_fg]=\"#FFFFFF\""));
        assert!(theme.contains("theme[hi_fg]=\"#63D1D6\""));
        assert!(theme.contains("theme[cpu_start]=\"#87D687\""));
        assert!(theme.contains("theme[cpu_end]=\"#FF6B6B\""));
    }

    #[test]
    fn test_generate_theme_key_count() {
        let palette = ColorPalette::sample();
        let theme = generate_theme(&palette);

        let key_lines: Vec<&str> = theme.lines().filter(|l| l.starts_with("theme[")).collect();
        // 14 main + 24 gradient (8 gradients × 3 each) = 38 keys
        assert_eq!(key_lines.len(), 38);
    }
}
