// SPDX-License-Identifier: GPL-3.0-only

//! fzf theme generator
//!
//! Generates an fzf color theme as a shell script that exports
//! `FZF_DEFAULT_OPTS` with `--color=` flags from the COSMIC palette.
//! Optionally manages shell integration (source line in `.bashrc`/`.zshrc`).

use std::fmt::Write;
use std::path::PathBuf;

use crate::colors::ColorPalette;

/// Generate fzf theme shell script content
pub fn generate_theme(palette: &ColorPalette) -> String {
    let mut out = String::with_capacity(512);
    out.push_str("#!/bin/sh\n");
    out.push_str("# COSMIC theme for fzf — auto-generated by COSMIC ORDER\n\n");

    out.push_str("export FZF_DEFAULT_OPTS=\"$FZF_DEFAULT_OPTS \\\n");
    let _ = writeln!(out, "  --color=bg:{} \\", palette.background);
    let _ = writeln!(out, "  --color=fg:{} \\", palette.foreground);
    let _ = writeln!(out, "  --color=hl:{} \\", palette.accent);
    let _ = writeln!(out, "  --color=bg+:{} \\", palette.colors[0]);
    let _ = writeln!(out, "  --color=fg+:{} \\", palette.foreground);
    let _ = writeln!(out, "  --color=hl+:{} \\", palette.accent);
    let _ = writeln!(out, "  --color=border:{} \\", palette.accent);
    let _ = writeln!(out, "  --color=info:{} \\", palette.colors[8]);
    let _ = writeln!(out, "  --color=marker:{} \\", palette.colors[1]);
    let _ = writeln!(out, "  --color=pointer:{} \\", palette.colors[1]);
    let _ = writeln!(out, "  --color=prompt:{} \\", palette.accent);
    let _ = writeln!(out, "  --color=spinner:{} \\", palette.colors[1]);
    let _ = writeln!(out, "  --color=header:{} \\", palette.colors[3]);
    let _ = writeln!(out, "  --color=gutter:{} \\", palette.background);
    let _ = writeln!(out, "  --color=query:{} \\", palette.foreground);
    let _ = writeln!(out, "  --color=separator:{} \\", palette.colors[8]);
    let _ = writeln!(out, "  --color=scrollbar:{}\"", palette.accent);

    out
}

/// Write the generated theme to `~/.config/cosmic-order/fzf-theme.sh`
pub async fn write_theme(palette: &ColorPalette) -> Result<PathBuf, std::io::Error> {
    let config_dir = cosmic_order_config_dir();
    tokio::fs::create_dir_all(&config_dir).await?;
    let path = config_dir.join("fzf-theme.sh");
    tokio::fs::write(&path, generate_theme(palette)).await?;
    Ok(path)
}

/// Source line added to shell rc files
const SOURCE_COMMENT: &str = "# COSMIC ORDER fzf theme";
const SOURCE_LINE: &str =
    "[[ -f ~/.config/cosmic-order/fzf-theme.sh ]] && source ~/.config/cosmic-order/fzf-theme.sh";

/// Enable fzf shell integration by adding source line to `.bashrc` and `.zshrc`
pub async fn enable_shell_integration() -> Result<(), std::io::Error> {
    let home = home_dir();
    for rc in &[home.join(".bashrc"), home.join(".zshrc")] {
        add_source_line(rc).await?;
    }
    Ok(())
}

/// Disable fzf shell integration by removing source line from `.bashrc` and `.zshrc`
pub async fn disable_shell_integration() -> Result<(), std::io::Error> {
    let home = home_dir();
    for rc in &[home.join(".bashrc"), home.join(".zshrc")] {
        remove_source_line(rc).await?;
    }
    Ok(())
}

/// Add source line to a shell rc file if not already present
async fn add_source_line(path: &std::path::Path) -> Result<(), std::io::Error> {
    let contents = match tokio::fs::read_to_string(path).await {
        Ok(c) => c,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(e),
    };

    if contents.contains(SOURCE_LINE) {
        return Ok(());
    }

    let mut new_contents = contents;
    if !new_contents.ends_with('\n') {
        new_contents.push('\n');
    }
    new_contents.push('\n');
    new_contents.push_str(SOURCE_COMMENT);
    new_contents.push('\n');
    new_contents.push_str(SOURCE_LINE);
    new_contents.push('\n');

    tokio::fs::write(path, new_contents).await
}

/// Remove source line (and its comment) from a shell rc file
async fn remove_source_line(path: &std::path::Path) -> Result<(), std::io::Error> {
    let contents = match tokio::fs::read_to_string(path).await {
        Ok(c) => c,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(e),
    };

    if !contents.contains(SOURCE_LINE) {
        return Ok(());
    }

    let new_lines: Vec<&str> = contents
        .lines()
        .filter(|line| {
            let trimmed = line.trim();
            trimmed != SOURCE_COMMENT && trimmed != SOURCE_LINE
        })
        .collect();

    let mut result = new_lines.join("\n");
    if !result.ends_with('\n') {
        result.push('\n');
    }

    tokio::fs::write(path, result).await
}

fn cosmic_order_config_dir() -> PathBuf {
    directories::BaseDirs::new().map_or_else(
        || {
            let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
            PathBuf::from(home).join(".config/cosmic-order")
        },
        |d| d.config_dir().join("cosmic-order"),
    )
}

fn home_dir() -> PathBuf {
    directories::BaseDirs::new().map_or_else(
        || {
            let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".to_string());
            PathBuf::from(home)
        },
        |d| d.home_dir().to_path_buf(),
    )
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    fn sample_palette() -> ColorPalette {
        ColorPalette {
            accent: "#63D1D6".to_string(),
            cursor: "#FFFFFF".to_string(),
            foreground: "#FFFFFF".to_string(),
            background: "#1B1B1B".to_string(),
            selection_foreground: "#1B1B1B".to_string(),
            selection_background: "#FFFFFF".to_string(),
            colors: [
                "#3B3B3B".to_string(),
                "#FF6B6B".to_string(),
                "#87D687".to_string(),
                "#FFD93D".to_string(),
                "#6B9FFF".to_string(),
                "#B87DFF".to_string(),
                "#63D1D6".to_string(),
                "#D4D4D4".to_string(),
                "#5A5A5A".to_string(),
                "#FF6B6B".to_string(),
                "#87D687".to_string(),
                "#FFD93D".to_string(),
                "#6B9FFF".to_string(),
                "#B87DFF".to_string(),
                "#63D1D6".to_string(),
                "#E8E8E8".to_string(),
            ],
        }
    }

    #[test]
    fn test_generate_theme_has_17_color_keys() {
        let palette = sample_palette();
        let theme = generate_theme(&palette);

        let color_lines: Vec<&str> = theme.lines().filter(|l| l.contains("--color=")).collect();
        assert_eq!(color_lines.len(), 17);
    }

    #[test]
    fn test_generate_theme_color_mapping() {
        let palette = sample_palette();
        let theme = generate_theme(&palette);

        assert!(theme.contains("--color=bg:#1B1B1B"));
        assert!(theme.contains("--color=fg:#FFFFFF"));
        assert!(theme.contains("--color=hl:#63D1D6"));
        assert!(theme.contains("--color=bg+:#3B3B3B"));
        assert!(theme.contains("--color=marker:#FF6B6B"));
        assert!(theme.contains("--color=header:#FFD93D"));
        assert!(theme.contains("--color=info:#5A5A5A"));
        assert!(theme.contains("--color=scrollbar:#63D1D6"));
    }

    #[test]
    fn test_generate_theme_is_valid_shell() {
        let palette = sample_palette();
        let theme = generate_theme(&palette);

        assert!(theme.starts_with("#!/bin/sh\n"));
        assert!(theme.contains("export FZF_DEFAULT_OPTS="));
    }

    #[test]
    fn test_source_line_format() {
        assert!(SOURCE_LINE.contains("source ~/.config/cosmic-order/fzf-theme.sh"));
        assert!(SOURCE_LINE.starts_with("[["));
    }
}
