// SPDX-License-Identifier: GPL-3.0-only

//! Neovim/LazyVim colorscheme generator
//!
//! Generates a tokyonight plugin spec with `on_colors` that maps
//! COSMIC palette colors into the tokyonight color system. The
//! `LazyVim` colorscheme setting and the live-reload command use a
//! configurable colorscheme name so users running their own theme
//! plugin can keep the rest of the sync pipeline.

use std::path::PathBuf;

use crate::colors::ColorPalette;
use crate::paths;

/// Generate `LazyVim` colorscheme plugin spec from a color palette
pub fn generate_theme(palette: &ColorPalette, colorscheme: &str) -> String {
    format!(
        r#"-- COSMIC theme for Neovim (tokyonight)
-- Auto-generated by COSMIC ORDER
return {{
  {{
    "folke/tokyonight.nvim",
    priority = 1000,
    opts = {{
      style = "night",
      transparent = false,
      terminal_colors = true,
      on_colors = function(colors)
        colors.bg = "{bg}"
        colors.bg_dark = "{bg_dark}"
        colors.bg_float = "{bg_float}"
        colors.fg = "{fg}"
        colors.cyan = "{cyan}"
        colors.blue = "{blue}"
        colors.green = "{green}"
        colors.yellow = "{yellow}"
        colors.orange = "{orange}"
        colors.red = "{red}"
        colors.magenta = "{magenta}"
      end,
    }},
  }},
  {{
    "LazyVim/LazyVim",
    opts = {{ colorscheme = "{colorscheme}" }},
  }},
}}"#,
        bg = palette.background,
        bg_dark = darken_hex(&palette.background),
        bg_float = lighten_hex(&palette.background),
        fg = palette.foreground,
        cyan = palette.accent,
        blue = palette.colors[4],
        green = palette.colors[2],
        yellow = palette.colors[3],
        orange = palette.colors[1], // red/orange from palette
        red = palette.colors[9],    // bright red
        magenta = palette.colors[5],
        colorscheme = colorscheme,
    )
}

/// Write the generated colorscheme to `~/.config/nvim/lua/plugins/colorscheme.lua`
///
/// Creates a `.bak` backup of the existing file before first overwrite.
pub async fn write_theme(
    palette: &ColorPalette,
    colorscheme: &str,
) -> Result<PathBuf, std::io::Error> {
    let path = paths::nvim_colorscheme();

    if let Some(parent) = path.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }

    // Backup existing file if no backup exists yet
    let backup_path = path.with_extension("lua.bak");
    if path.exists() && !backup_path.exists() {
        tokio::fs::copy(&path, &backup_path).await?;
        tracing::info!("Backed up colorscheme to {}", backup_path.display());
    }

    tokio::fs::write(&path, generate_theme(palette, colorscheme)).await?;
    Ok(path)
}

/// Darken a hex color by reducing each channel by ~40%
#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
fn darken_hex(hex: &str) -> String {
    let Some((r, g, b)) = crate::colors::hex_to_rgb(hex) else {
        return hex.to_string();
    };
    let darken = |v: u8| (f32::from(v) * 0.6) as u8;
    format!("#{:02X}{:02X}{:02X}", darken(r), darken(g), darken(b))
}

/// Lighten a hex color by blending toward white by ~20%
#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
fn lighten_hex(hex: &str) -> String {
    let Some((r, g, b)) = crate::colors::hex_to_rgb(hex) else {
        return hex.to_string();
    };
    let lighten = |v: u8| {
        let f = f32::from(v);
        (255.0 - f).mul_add(0.15, f) as u8
    };
    format!("#{:02X}{:02X}{:02X}", lighten(r), lighten(g), lighten(b))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_theme_valid_lua() {
        let palette = ColorPalette::sample();
        let theme = generate_theme(&palette, "tokyonight");

        // Verify it's a valid Lua return statement
        assert!(theme.starts_with("-- COSMIC theme"));
        assert!(theme.contains("return {"));
        assert!(theme.contains("\"folke/tokyonight.nvim\""));
        assert!(theme.contains("colorscheme = \"tokyonight\""));
    }

    #[test]
    fn test_generate_theme_colors() {
        let palette = ColorPalette::sample();
        let theme = generate_theme(&palette, "tokyonight");

        assert!(theme.contains("colors.bg = \"#1B1B1B\""));
        assert!(theme.contains("colors.fg = \"#FFFFFF\""));
        assert!(theme.contains("colors.cyan = \"#63D1D6\""));
        assert!(theme.contains("colors.blue = \"#6B9FFF\""));
        assert!(theme.contains("colors.green = \"#87D687\""));
    }

    #[test]
    fn test_generate_theme_custom_colorscheme() {
        let palette = ColorPalette::sample();
        let theme = generate_theme(&palette, "catppuccin");
        assert!(theme.contains("colorscheme = \"catppuccin\""));
        assert!(!theme.contains("colorscheme = \"tokyonight\""));
    }

    #[test]
    fn test_darken_hex() {
        // #1B1B1B * 0.6 ≈ #101010
        let darkened = darken_hex("#1B1B1B");
        assert!(darkened.starts_with('#'));
        assert_eq!(darkened.len(), 7);
        // Just verify it's darker (smaller values)
        let (r, _, _) = crate::colors::hex_to_rgb(&darkened).unwrap();
        assert!(r < 0x1B);
    }

    #[test]
    fn test_lighten_hex() {
        let lightened = lighten_hex("#1B1B1B");
        assert!(lightened.starts_with('#'));
        assert_eq!(lightened.len(), 7);
        let (r, _, _) = crate::colors::hex_to_rgb(&lightened).unwrap();
        assert!(r > 0x1B);
    }
}
