// SPDX-License-Identifier: GPL-3.0-only

//! Zellij theme generator
//!
//! Generates a Zellij theme block from the COSMIC color palette
//! and updates the user's Zellij config file.

use std::fmt::Write;
use std::path::PathBuf;

use crate::colors::{ColorPalette, hex_to_rgb};
use crate::paths;

/// Format a hex color as Zellij decimal RGB (space-separated)
fn decimal_rgb(hex: &str) -> String {
    match hex_to_rgb(hex) {
        Some((r, g, b)) => format!("{r} {g} {b}"),
        None => "0 0 0".to_string(),
    }
}

/// Generate the Zellij themes block content
pub fn generate_theme_block(palette: &ColorPalette) -> String {
    let mut out = String::with_capacity(512);
    out.push_str("// COSMIC theme for Zellij — auto-generated by COSMIC ORDER\n");
    out.push_str("themes {\n");
    out.push_str("    cosmic-synced {\n");
    let _ = writeln!(out, "        fg {}", decimal_rgb(&palette.foreground));
    let _ = writeln!(out, "        bg {}", decimal_rgb(&palette.background));
    let _ = writeln!(out, "        black {}", decimal_rgb(&palette.colors[0]));
    let _ = writeln!(out, "        red {}", decimal_rgb(&palette.colors[1]));
    let _ = writeln!(out, "        green {}", decimal_rgb(&palette.colors[2]));
    let _ = writeln!(out, "        yellow {}", decimal_rgb(&palette.colors[3]));
    let _ = writeln!(out, "        blue {}", decimal_rgb(&palette.colors[4]));
    let _ = writeln!(out, "        magenta {}", decimal_rgb(&palette.colors[5]));
    let _ = writeln!(out, "        orange {}", decimal_rgb(&palette.colors[1]));
    let _ = writeln!(out, "        cyan {}", decimal_rgb(&palette.accent));
    let _ = writeln!(out, "        white {}", decimal_rgb(&palette.colors[7]));
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

/// Write theme to `~/.config/zellij/config.kdl`
///
/// Replaces existing `themes { cosmic-synced { ... } }` block if present,
/// otherwise appends. Also sets `theme "cosmic-synced"` at the top.
pub async fn write_theme(palette: &ColorPalette) -> Result<PathBuf, std::io::Error> {
    let config_path = paths::zellij_config();

    if let Some(parent) = config_path.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }

    let contents = match tokio::fs::read_to_string(&config_path).await {
        Ok(c) => c,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(e),
    };

    let theme_block = generate_theme_block(palette);
    let new_contents = update_config(&contents, &theme_block);

    tokio::fs::write(&config_path, new_contents).await?;
    Ok(config_path)
}

/// Update config string: replace/add theme line and themes block
fn update_config(contents: &str, theme_block: &str) -> String {
    let mut lines: Vec<String> = Vec::new();
    let mut found_theme_line = false;
    let mut skip_themes_block = false;
    let mut brace_depth: i32 = 0;
    let mut found_themes_block = false;

    for line in contents.lines() {
        let trimmed = line.trim();

        // Skip inside an existing themes { cosmic-synced { ... } } block
        if skip_themes_block {
            for ch in trimmed.chars() {
                if ch == '{' {
                    brace_depth += 1;
                }
                if ch == '}' {
                    brace_depth -= 1;
                }
            }
            if brace_depth <= 0 {
                skip_themes_block = false;
            }
            continue;
        }

        // Replace existing `theme "..."` line
        if trimmed.starts_with("theme ") && trimmed.contains('"') {
            lines.push("theme \"cosmic-synced\"".to_string());
            found_theme_line = true;
            continue;
        }

        // Detect start of our themes block (comment marker)
        if trimmed == "// COSMIC theme for Zellij — auto-generated by COSMIC ORDER" {
            skip_themes_block = true;
            brace_depth = 0;
            found_themes_block = true;
            continue;
        }

        // Also detect a bare `themes {` that contains `cosmic-synced`
        // We look ahead by checking if next content is cosmic-synced
        if trimmed.starts_with("themes {") || trimmed == "themes{" {
            // Check if this is a themes block we should replace
            // We'll use a simpler heuristic: if there's already a COSMIC comment above,
            // it was caught. Otherwise leave non-COSMIC themes blocks alone.
            lines.push(line.to_string());
            continue;
        }

        lines.push(line.to_string());
    }

    // Set theme line at top if not found
    if !found_theme_line {
        // Find the first non-comment, non-empty line to insert before
        let insert_pos = lines
            .iter()
            .position(|l| {
                let t = l.trim();
                !t.is_empty() && !t.starts_with("//")
            })
            .unwrap_or(0);
        lines.insert(insert_pos, "theme \"cosmic-synced\"".to_string());
        // Add blank line after if the next line isn't blank
        if lines.get(insert_pos + 1).is_some_and(|l| !l.is_empty()) {
            lines.insert(insert_pos + 1, String::new());
        }
    }

    // Append or replace themes block
    if found_themes_block {
        // Insert the new block where the old one was removed
        // Just append at end since we removed the old one
        if lines.last().is_some_and(|l| !l.is_empty()) {
            lines.push(String::new());
        }
        lines.push(theme_block.trim_end().to_string());
    } else {
        // Append at end
        if lines.last().is_some_and(|l| !l.is_empty()) {
            lines.push(String::new());
        }
        lines.push(theme_block.trim_end().to_string());
    }

    // Ensure trailing newline
    lines.push(String::new());
    lines.join("\n")
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    fn sample_palette() -> ColorPalette {
        ColorPalette {
            accent: "#63D1D6".to_string(),
            cursor: "#FFFFFF".to_string(),
            foreground: "#F8F8F8".to_string(),
            background: "#1A1A1A".to_string(),
            selection_foreground: "#1A1A1A".to_string(),
            selection_background: "#F8F8F8".to_string(),
            colors: [
                "#161616".to_string(),
                "#FFA09A".to_string(),
                "#5EDB8B".to_string(),
                "#F7E062".to_string(),
                "#63D0DF".to_string(),
                "#E79CFE".to_string(),
                "#63D1D6".to_string(),
                "#DEDEDE".to_string(),
                "#5A5A5A".to_string(),
                "#FFA09A".to_string(),
                "#5EDB8B".to_string(),
                "#F7E062".to_string(),
                "#63D0DF".to_string(),
                "#E79CFE".to_string(),
                "#63D1D6".to_string(),
                "#E8E8E8".to_string(),
            ],
        }
    }

    #[test]
    fn test_generate_theme_block_format() {
        let palette = sample_palette();
        let block = generate_theme_block(&palette);

        // Verify decimal RGB format (not hex)
        assert!(block.contains("fg 248 248 248"));
        assert!(block.contains("bg 26 26 26"));
        assert!(block.contains("black 22 22 22"));
        assert!(block.contains("red 255 160 154"));
        assert!(block.contains("green 94 219 139"));
        assert!(block.contains("cyan 99 209 214"));
    }

    #[test]
    fn test_generate_theme_block_structure() {
        let palette = sample_palette();
        let block = generate_theme_block(&palette);

        assert!(block.contains("themes {"));
        assert!(block.contains("cosmic-synced {"));
        // 11 color lines
        let color_lines: Vec<&str> = block
            .lines()
            .filter(|l| {
                let t = l.trim();
                !t.is_empty()
                    && !t.starts_with("//")
                    && !t.starts_with("themes")
                    && !t.starts_with("cosmic-synced")
                    && !t.starts_with('}')
            })
            .collect();
        assert_eq!(color_lines.len(), 11);
    }

    #[test]
    fn test_update_config_fresh() {
        let result = update_config(
            "",
            "themes {\n    cosmic-synced {\n        fg 255 255 255\n    }\n}\n",
        );
        assert!(result.contains("theme \"cosmic-synced\""));
        assert!(result.contains("themes {"));
    }

    #[test]
    fn test_update_config_replace_theme_line() {
        let existing = "theme \"tokyo-night\"\n\ndefault_layout \"compact\"\n";
        let result = update_config(existing, "themes {\n    cosmic-synced {\n    }\n}\n");
        assert!(result.contains("theme \"cosmic-synced\""));
        assert!(!result.contains("tokyo-night"));
    }

    #[test]
    fn test_update_config_replaces_old_block() {
        let existing = "theme \"cosmic-synced\"\n\n// COSMIC theme for Zellij — auto-generated by COSMIC ORDER\nthemes {\n    cosmic-synced {\n        fg 0 0 0\n    }\n}\n\nother_config true\n";
        let new_block = "// COSMIC theme for Zellij — auto-generated by COSMIC ORDER\nthemes {\n    cosmic-synced {\n        fg 255 255 255\n    }\n}\n";
        let result = update_config(existing, new_block);
        assert!(result.contains("fg 255 255 255"));
        assert!(!result.contains("fg 0 0 0"));
        assert!(result.contains("other_config true"));
    }

    #[test]
    fn test_decimal_rgb() {
        assert_eq!(decimal_rgb("#FF0000"), "255 0 0");
        assert_eq!(decimal_rgb("#1A1A1A"), "26 26 26");
        assert_eq!(decimal_rgb("#F8F8F8"), "248 248 248");
        assert_eq!(decimal_rgb("invalid"), "0 0 0");
    }
}
