// SPDX-License-Identifier: GPL-3.0-only

//! Color palette extraction, conversion utilities, and serialization
//!
//! Extracts terminal-compatible colors from the active COSMIC theme
//! and serializes them to the OMARCHY `colors.toml` format.

use std::fmt::Write;
use std::path::PathBuf;

use cosmic::cosmic_theme::palette::{Srgb, Srgba};
use cosmic::theme;

use crate::paths;

/// Terminal color palette extracted from COSMIC theme
#[derive(Debug, Clone)]
pub struct ColorPalette {
    pub accent: String,
    pub cursor: String,
    pub foreground: String,
    pub background: String,
    pub selection_foreground: String,
    pub selection_background: String,
    pub colors: [String; 16],
}

impl ColorPalette {
    /// Extract color palette from the active COSMIC theme
    pub fn from_cosmic() -> Self {
        let active = theme::active();
        let cosmic = active.cosmic();
        let palette = &cosmic.palette;

        let hex = |c: &Srgba| srgba_to_hex(c);

        let foreground = hex(&cosmic.primary.on);
        let background = hex(&cosmic.background.base);

        Self {
            accent: hex(&cosmic.accent.base),
            cursor: foreground.clone(),
            foreground: foreground.clone(),
            background: background.clone(),
            selection_foreground: background.clone(),
            selection_background: foreground.clone(),
            colors: [
                hex(&palette.neutral_2),     // 0: black
                hex(&palette.bright_red),    // 1: red
                hex(&palette.bright_green),  // 2: green
                hex(&palette.accent_yellow), // 3: yellow
                hex(&palette.accent_blue),   // 4: blue
                hex(&palette.accent_purple), // 5: magenta
                hex(&cosmic.accent.base),    // 6: cyan (accent)
                hex(&palette.neutral_8),     // 7: white
                hex(&palette.neutral_4),     // 8: bright black
                hex(&palette.bright_red),    // 9: bright red
                hex(&palette.bright_green),  // 10: bright green
                hex(&palette.accent_yellow), // 11: bright yellow
                hex(&palette.accent_blue),   // 12: bright blue
                hex(&palette.accent_purple), // 13: bright magenta
                hex(&cosmic.accent.base),    // 14: bright cyan
                hex(&palette.neutral_9),     // 15: bright white
            ],
        }
    }

    /// Serialize to OMARCHY `colors.toml` format
    pub fn to_toml(&self) -> String {
        let mut out = String::with_capacity(512);
        out.push_str("# COSMIC theme colors (OMARCHY format)\n");
        out.push_str("# Auto-generated by COSMIC ORDER\n\n");

        let _ = writeln!(out, "accent = \"{}\"", self.accent);
        let _ = writeln!(out, "cursor = \"{}\"", self.cursor);
        let _ = writeln!(out, "foreground = \"{}\"", self.foreground);
        let _ = writeln!(out, "background = \"{}\"", self.background);
        let _ = writeln!(
            out,
            "selection_foreground = \"{}\"",
            self.selection_foreground
        );
        let _ = writeln!(
            out,
            "selection_background = \"{}\"",
            self.selection_background
        );

        out.push_str("\n# Terminal palette (16 colors)\n");
        for (i, color) in self.colors.iter().enumerate() {
            let _ = writeln!(out, "color{i} = \"{color}\"");
        }

        out
    }

    /// Write palette to `~/.config/cosmic-order/colors.toml`
    pub async fn save(&self) -> Result<PathBuf, std::io::Error> {
        let config_dir = paths::cosmic_order_config_dir();
        tokio::fs::create_dir_all(&config_dir).await?;
        let path = config_dir.join("colors.toml");
        tokio::fs::write(&path, self.to_toml()).await?;
        Ok(path)
    }

    /// Create a sample palette for testing
    #[cfg(test)]
    pub fn sample() -> Self {
        Self {
            accent: "#63D1D6".to_string(),
            cursor: "#FFFFFF".to_string(),
            foreground: "#FFFFFF".to_string(),
            background: "#1B1B1B".to_string(),
            selection_foreground: "#1B1B1B".to_string(),
            selection_background: "#FFFFFF".to_string(),
            colors: [
                "#3B3B3B".to_string(),
                "#FF6B6B".to_string(),
                "#87D687".to_string(),
                "#FFD93D".to_string(),
                "#6B9FFF".to_string(),
                "#B87DFF".to_string(),
                "#63D1D6".to_string(),
                "#D4D4D4".to_string(),
                "#5A5A5A".to_string(),
                "#FF6B6B".to_string(),
                "#87D687".to_string(),
                "#FFD93D".to_string(),
                "#6B9FFF".to_string(),
                "#B87DFF".to_string(),
                "#63D1D6".to_string(),
                "#E8E8E8".to_string(),
            ],
        }
    }
}

/// Parse a hex color string (`#RRGGBB`) to decimal RGB tuple
pub fn hex_to_rgb(hex: &str) -> Option<(u8, u8, u8)> {
    let hex = hex.strip_prefix('#')?;
    if hex.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&hex[0..2], 16).ok()?;
    let g = u8::from_str_radix(&hex[2..4], 16).ok()?;
    let b = u8::from_str_radix(&hex[4..6], 16).ok()?;
    Some((r, g, b))
}

/// Parse a hex string (#RRGGBB or RRGGBB) to Srgb
pub fn parse_hex_to_srgb(hex: &str) -> Option<Srgb> {
    let (r, g, b) = hex_to_rgb(hex)?;
    Some(Srgb::new(
        f32::from(r) / 255.0,
        f32::from(g) / 255.0,
        f32::from(b) / 255.0,
    ))
}

/// Format an Srgb color as a hex string (#RRGGBB)
#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
pub fn srgb_to_hex(c: &Srgb) -> String {
    format!(
        "#{:02X}{:02X}{:02X}",
        (c.red * 255.0) as u8,
        (c.green * 255.0) as u8,
        (c.blue * 255.0) as u8
    )
}

/// Format an Srgba color as a hex string (#RRGGBB)
#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
pub fn srgba_to_hex(c: &Srgba) -> String {
    format!(
        "#{:02X}{:02X}{:02X}",
        (c.red * 255.0) as u8,
        (c.green * 255.0) as u8,
        (c.blue * 255.0) as u8
    )
}

/// Pack (r, g, b) as u8 values into a single u32
#[allow(clippy::cast_lossless)]
pub const fn pack_rgb(r: u8, g: u8, b: u8) -> u32 {
    (r as u32) << 16 | (g as u32) << 8 | b as u32
}

/// Unpack a u32 to Srgb (0.0–1.0)
#[allow(clippy::cast_possible_truncation, clippy::cast_precision_loss)]
pub fn unpack_rgb(packed: u32) -> Srgb {
    let r = ((packed >> 16) & 0xFF) as f32 / 255.0;
    let g = ((packed >> 8) & 0xFF) as f32 / 255.0;
    let b = (packed & 0xFF) as f32 / 255.0;
    Srgb::new(r, g, b)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn test_to_toml_format() {
        let palette = ColorPalette::sample();
        let toml = palette.to_toml();

        // Should have 22 key-value lines (6 named + 16 palette)
        let kv_lines: Vec<&str> = toml
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect();
        assert_eq!(kv_lines.len(), 22);

        // Verify format matches OMARCHY style
        assert!(toml.contains("accent = \"#63D1D6\""));
        assert!(toml.contains("foreground = \"#FFFFFF\""));
        assert!(toml.contains("background = \"#1B1B1B\""));
        assert!(toml.contains("color0 = \"#3B3B3B\""));
        assert!(toml.contains("color15 = \"#E8E8E8\""));
    }

    #[test]
    fn test_all_colors_are_hex() {
        let palette = ColorPalette::sample();
        let all_colors = [
            &palette.accent,
            &palette.cursor,
            &palette.foreground,
            &palette.background,
            &palette.selection_foreground,
            &palette.selection_background,
        ];

        for color in all_colors {
            assert!(color.starts_with('#'), "Not hex: {color}");
            assert_eq!(color.len(), 7, "Wrong hex length: {color}");
        }

        for color in &palette.colors {
            assert!(color.starts_with('#'), "Not hex: {color}");
            assert_eq!(color.len(), 7, "Wrong hex length: {color}");
        }
    }

    #[test]
    fn test_hex_to_rgb() {
        assert_eq!(hex_to_rgb("#FF0000"), Some((255, 0, 0)));
        assert_eq!(hex_to_rgb("#00FF00"), Some((0, 255, 0)));
        assert_eq!(hex_to_rgb("#1A1A1A"), Some((26, 26, 26)));
        assert_eq!(hex_to_rgb("#F8F8F8"), Some((248, 248, 248)));
        assert_eq!(hex_to_rgb("invalid"), None);
        assert_eq!(hex_to_rgb("#FFF"), None);
    }

    #[test]
    fn test_parse_hex_to_srgb() {
        let c = parse_hex_to_srgb("#FF0000").unwrap();
        assert!((c.red - 1.0).abs() < 0.01);
        assert!(c.green.abs() < 0.01);
        assert!(c.blue.abs() < 0.01);

        assert!(parse_hex_to_srgb("invalid").is_none());
    }

    #[test]
    fn test_srgb_to_hex() {
        let c = Srgb::new(1.0, 0.0, 0.0);
        assert_eq!(srgb_to_hex(&c), "#FF0000");
    }

    #[test]
    fn test_srgba_to_hex() {
        let c = Srgba::new(0.0, 1.0, 0.0, 1.0);
        assert_eq!(srgba_to_hex(&c), "#00FF00");
    }

    #[test]
    fn test_pack_unpack_roundtrip() {
        let packed = pack_rgb(0x1B, 0x2C, 0x3D);
        let c = unpack_rgb(packed);
        let hex = srgb_to_hex(&c);
        assert_eq!(hex, "#1B2C3D");
    }
}
